### Create Quizzes - request body
POST http://localhost:4000/quizzes
Content-Type: application/json

{
  "title": "TypeScript Fundamental",
  "questions": [{
    "text": "TypeScript type annotations are checked during the program's runtime execution.",
    "type": "BOOLEAN",
    "options": ["true", "false"],
    "correctAnswerBoolean": false
  }]
}

### Fetch quizzes — response
GET http://localhost:4000/quizzes

### Fetch quizzes by ID  — response
GET http://localhost:4000/quizzes/6728da49-b149-4feb-bd09-bdc9669dc9b2

### Delete quizzes by ID  — response
DELETE http://localhost:4000/quizzes/7b0b3833-290f-4993-9445-fdbab73ae97e